/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uploads;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ksa
 */
public class TelaUp extends javax.swing.JFrame {

    File arq;

    /**
     * Creates new form TelaUp
     */
    public TelaUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnBaixar = new javax.swing.JButton();
        txtBaixar = new javax.swing.JTextField();
        txtEnviar = new javax.swing.JLabel();
        selAquivo = new javax.swing.JButton();
        txtProcurar = new javax.swing.JTextField();
        txtEnviar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtbusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBaixar.setText("Baixar");

        txtBaixar.setText("Baixar Arquivos");

        txtEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEnviar.setText("Selecionar Arquivo");

        selAquivo.setText("Procurar...");
        selAquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selAquivoActionPerformed(evt);
            }
        });

        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });

        txtEnviar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEnviar1.setText("Arquivos Diretorio");

        txtbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selAquivo)
                                .addGap(34, 34, 34)
                                .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEnviar)
                            .addComponent(txtEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar))
                                .addGap(159, 159, 159)
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnBaixar)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(txtEnviar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selAquivo)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnviar1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaixar)
                    .addComponent(txtBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:

        System.out.println("Entrou ak");
        String caminho = getClass().getResource("../imagens/").toString().substring(5);
        File outputfile = new File(caminho);
        System.out.println("Caminho" + caminho);
        String nameArquivo = outputfile.getName();

        //System.out.println("Entrou 2 " + nameArquivo);
        //System.out.println("gggggggg "+ arq.getName());
        File arquivo = new File(caminho + arq.getName());
        try {
            arquivo.createNewFile();
            //arquivo
        } catch (IOException ex) {
            Logger.getLogger(TelaUp.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            outputfile.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(TelaUp.class.getName()).log(Level.SEVERE, null, ex);
        }

            // JOptionPane.showMessageDialog(rootPane, "Imagem enviada com sucesso");

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void selAquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selAquivoActionPerformed
        // TODO add your handling code here:
        JFileChooser selArquivo = new JFileChooser();
        int res = selArquivo.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(null, "Selecionado com Sucesso.");

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
        File arquivo = selArquivo.getSelectedFile();
        arq = arquivo;
        txtProcurar.setText(arquivo.getPath()); // coloca caminho do arquivo.
        System.out.println("TETSTETSTE " + arquivo.getName());

    }//GEN-LAST:event_selAquivoActionPerformed

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtProcurarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        String caminho = getClass().getResource("../imagens/").toString().substring(5);
        
        File busca = new File (caminho);
           String listaD = "";
        String[] list = busca.list();
        for(String arquivos: list){
            
            //System.out.println(arquivos);
            
            //System.out.print("lisfiles"+busca.listFiles() );
            int i;
            //System.out.print("teste chritian "+ busca.getParent());
         
            listaD+=arquivos+"\r\n";
            
//            //int qnt = busca.listFiles().length;
//            for ( i=0; i <= busca.listFiles().length ; i++){
//                
//               
                System.out.println(arquivos);
//                
//            }
          
            
            
            
            
        }
           txtbusca.setText(listaD);
            System.out.println("listaD"+ listaD);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscaActionPerformed
//       String caminho = getClass().getResource("../imagens/").toString().substring(5);
//        
//        File file = new File(caminho);
//        System.out.println("Caminho "+ caminho);
//       File[] arquivos = file.listFiles();
//
//       for (File fileTmp : arquivos) {
//     System.out.println("da net "+fileTmp.getName());
//     
//   
//   }
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtbuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaixar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton selAquivo;
    private javax.swing.JTextField txtBaixar;
    private javax.swing.JLabel txtEnviar;
    private javax.swing.JLabel txtEnviar1;
    private javax.swing.JTextField txtProcurar;
    private javax.swing.JTextField txtbusca;
    // End of variables declaration//GEN-END:variables
}
